version: '3.1'
services:
  swag:
    image: linuxserver/swag
    container_name: swag
    depends_on:
      - wordpress
    volumes:
      - ./config:/config
      - ./default:/config/nginx/site-confs/default
    environment:
      - EMAIL=jpgomezt@eafit.edu.co
      - URL=wordpress-pampa.tk
      - SUBDOMAINS=www
      - VALIDATION=http
      - TZ=America/Bogota
      - PUID=500
      - PGID=500
    ports:
      - "443:443"
      - "80:80"
  wordpress:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db 
      WORDPRESS_DB_USER: exampleuser 
      WORDPRESS_DB_PASSWORD: examplepass 
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb 
      MYSQL_USER: exampleuser 
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1' 
    volumes:
      - db:/var/lib/mysql
volumes:
  wordpress:
  db: